<a href="https://colab.research.google.com/github/cysorianoc/IBM_Machine_Learning/blob/main/Course_1_ML_NB_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Machine Learning Foundation

## Section 1, Part a: Reading Data

### Learning Objective(s)

 - Create a SQL database connection to a sample SQL database, and read records from that database
 - Explore common input parameters

### Packages

 - [Pandas](https://pandas.pydata.org/pandas-docs/stable/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0232ENSkillsNetwork837-2023-01-01)
 - [Pandas.read_sql](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_sql.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0232ENSkillsNetwork837-2023-01-01)
 - [SQLite3](https://docs.python.org/3.6/library/sqlite3.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0232ENSkillsNetwork837-2023-01-01)

## Simple data reads

Structured Query Language (SQL) is an [ANSI specification](https://docs.oracle.com/database/121/SQLRF/ap_standard_sql001.htm?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0232ENSkillsNetwork837-2023-01-01#SQLRF55514), implemented by various databases. SQL is a powerful format for interacting with large databases efficiently, and SQL allows for a consistent experience across a large market of databases. We'll be using sqlite, a lightweight and somewhat restricted version of sql for this example. sqlite uses a slightly modified version of SQL, which may be different than what you're used to.

In [ ]:
# Imports
import sqlite3 as sq3
import pandas.io.sql as pds
import pandas as pd

### Database connections

Our first step will be to create a connection to our SQL database. A few common SQL databases used with Python include:

 - Microsoft SQL Server
 - Postgres
 - MySQL
 - AWS Redshift
 - AWS Aurora
 - Oracle DB
 - Terradata
 - Db2 Family
 - Many, many others

Each of these databases will require a slightly different setup, and may require credentials (username & password), tokens, or other access requirements. We'll be using `sqlite3` to connect to our database, but other connection packages include:

 - [`SQLAlchemy`](https://www.sqlalchemy.org/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0232ENSkillsNetwork837-2023-01-01) (most common)
 - [`psycopg2`](http://initd.org/psycopg/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0232ENSkillsNetwork837-2023-01-01)
 - [`MySQLdb`](http://mysql-python.sourceforge.net/MySQLdb.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML0232ENSkillsNetwork837-2023-01-01)

In [ ]:
# Download the database
!wget -P data https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML0232EN-SkillsNetwork/asset/classic_rock.db

--2025-07-06 18:20:42--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML0232EN-SkillsNetwork/asset/classic_rock.db
Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 169.63.118.104
Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|169.63.118.104|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5652480 (5.4M) [binary/octet-stream]
Saving to: ‘data/classic_rock.db’

classic_rock.db     100%[===================>]   5.39M  8.08MB/s    in 0.7s

2025-07-06 18:20:44 (8.08 MB/s) - ‘data/classic_rock.db’ saved [5652480/5652480]

In [ ]:
# Initialize path to SQLite databasejdbc:sqlite:/C:/__tmp/test/sqlite/jdbcTest.db
path = 'data/classic_rock.db'
con = sq3.Connection(path)

# We now have a live connection to our SQL database

### 🔌 What is `con` and Why Do We Use It?

`con` is short for **connection**. It refers to the **connection object** that links your Python code to the database.

Before you can run SQL queries from Python, you need to connect to the database file (for example, a `.sqlite` file). This is usually done like this:

```python
import sqlite3
con = sqlite3.connect("my_database.sqlite")

In [ ]:
con

## We can add a step to see what is inside the database
### So it is possible to pass a query to see the tables available.

In [ ]:
# List all tables in the database. In case of not knowing what is inside
tables_query = "SELECT name FROM sqlite_master WHERE type='table';"    # sqlite_master is a special table that stores information about the database structure.
tables_df = pd.read_sql(tables_query, con)                             # pd.read_sql() is a pandas function that runs the SQL query and returns the result as a DataFrame (a table-like structure in pandas).
print("Available tables in the database:")
print(tables_df)

Available tables in the database:
         name
0  rock_songs
1  rock_plays

### Reading data

Now that we've got a connection to our database, we can perform queries, and load their results in as Pandas DataFrames

In [ ]:
# Write the query
query = '''
SELECT *
FROM rock_songs;
'''

# Execute the query
observations = pd.read_sql(query, con)

observations.head()

                     Song        Artist  Release_Year  PlayCount
0        Caught Up in You   .38 Special        1982.0         82
1         Hold On Loosely   .38 Special        1981.0         85
2  Rockin' Into the Night   .38 Special        1980.0         18
3       Art For Arts Sake          10cc        1975.0          1
4              Kryptonite  3 Doors Down        2000.0         13

In [ ]:
# We can also run any supported SQL query
# Write the query
query = '''
SELECT Artist, Release_Year, COUNT(*) AS num_songs, AVG(PlayCount) AS avg_plays
    FROM rock_songs
    GROUP BY Artist, Release_Year
    ORDER BY num_songs desc;
'''

# Execute the query
observations = pd.read_sql(query, con)

observations.head()

         Artist  Release_Year  num_songs  avg_plays
0   The Beatles        1967.0         23   6.565217
1  Led Zeppelin        1969.0         18  21.000000
2   The Beatles        1965.0         15   3.800000
3   The Beatles        1968.0         13  13.000000
4   The Beatles        1969.0         13  15.000000

## Common parameters

There are a number of common paramters that can be used to read in SQL data with formatting:

 - coerce_float: Attempt to force numbers into floats
 - parse_dates: List of columns to parse as dates
 - chunksize: Number of rows to include in each chunk

Let's have a look at using some of these parameters

In [ ]:
query='''
SELECT Artist, Release_Year, COUNT(*) AS num_songs, AVG(PlayCount) AS avg_plays
    FROM rock_songs
    GROUP BY Artist, Release_Year
    ORDER BY num_songs desc;
'''

# Execute the query
observations_generator = pds.read_sql(query,
                            con,
                            coerce_float=True, # Doesn't efefct this dataset, because floats were correctly parsed
                            parse_dates=['Release_Year'], # Parse `Release_Year` as a date
                            chunksize=5 # Allows for streaming results as a series of shorter tables
                           )

for index, observations in enumerate(observations_generator):
    if index < 5:
        print(f'Observations index: {index}'.format(index))
        display(observations)

Observations index: 0

         Artist        Release_Year  num_songs  avg_plays
0   The Beatles 1970-01-01 00:32:47         23   6.565217
1  Led Zeppelin 1970-01-01 00:32:49         18  21.000000
2   The Beatles 1970-01-01 00:32:45         15   3.800000
3   The Beatles 1970-01-01 00:32:48         13  13.000000
4   The Beatles 1970-01-01 00:32:49         13  15.000000

Observations index: 1

         Artist        Release_Year  num_songs  avg_plays
0  Led Zeppelin 1970-01-01 00:32:50         12  13.166667
1  Led Zeppelin 1970-01-01 00:32:55         12  14.166667
2    Pink Floyd 1970-01-01 00:32:59         11  41.454545
3    Pink Floyd 1970-01-01 00:32:53         10  29.100000
4     The Doors 1970-01-01 00:32:47         10  28.900000

Observations index: 2

          Artist        Release_Year  num_songs  avg_plays
0  Fleetwood Mac 1970-01-01 00:32:57          9  35.666667
1   Jimi Hendrix 1970-01-01 00:32:47          9  24.888889
2    The Beatles 1970-01-01 00:32:43          9   2.444444
3    The Beatles 1970-01-01 00:32:44          9   3.111111
4     Elton John 1970-01-01 00:32:53          8  18.500000

Observations index: 3

           Artist        Release_Year  num_songs  avg_plays
0    Led Zeppelin 1970-01-01 00:32:51          8  47.750000
1    Led Zeppelin 1970-01-01 00:32:53          8  34.125000
2          Boston 1970-01-01 00:32:56          7  69.285714
3  Rolling Stones 1970-01-01 00:32:49          7  36.142857
4       Van Halen 1970-01-01 00:32:58          7  51.142857

Observations index: 4

                         Artist        Release_Year  num_songs  avg_plays
0             Bruce Springsteen 1970-01-01 00:32:55          6   7.666667
1             Bruce Springsteen 1970-01-01 00:33:04          6  11.500000
2  Creedence Clearwater Revival 1970-01-01 00:32:49          6  23.833333
3  Creedence Clearwater Revival 1970-01-01 00:32:50          6  18.833333
4                   Def Leppard 1970-01-01 00:33:07          6  32.000000

### Machine Learning Foundation (C) 2020 IBM Corporation

# Another example

In [ ]:
#Step 1  Download a database
!wget -P data https://www.timestored.com/data/sample/chinook.db

--2025-07-06 18:43:23--  https://www.timestored.com/data/sample/chinook.db
Resolving www.timestored.com (www.timestored.com)... 139.162.217.116
Connecting to www.timestored.com (www.timestored.com)|139.162.217.116|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 884736 (864K)
Saving to: ‘data/chinook.db’

chinook.db          100%[===================>] 864.00K  1.45MB/s    in 0.6s

2025-07-06 18:43:24 (1.45 MB/s) - ‘data/chinook.db’ saved [884736/884736]

In [ ]:
import sqlite3 as sq3
import pandas as pd

# Path to the SQLite database
path = '/content/data/chinook.db'
con2 = sq3.connect(path)  # Fixed connection method

# Step 1: List all tables in the database. In case of not knowing what is inside
tables_query = "SELECT name FROM sqlite_master WHERE type='table';"
tables_df = pd.read_sql(tables_query, con2)
print("Available tables in the database:")
print(tables_df)

Available tables in the database:
               name
0            albums
1   sqlite_sequence
2           artists
3         customers
4         employees
5            genres
6          invoices
7     invoice_items
8       media_types
9         playlists
10   playlist_track
11           tracks
12     sqlite_stat1

In [ ]:
# Step 2: Once you know a table name, you can query it like this:
# Replace 'your_table_name' with an actual table name from the printed list
query = '''
SELECT *
FROM albums
LIMIT 5;
'''
# observations = pd.read_sql(query, con2)
# print(observations)

In [ ]:
observations = pd.read_sql(query, con2)

In [ ]:
print(observations)

   AlbumId                                  Title  ArtistId
0        1  For Those About To Rock We Salute You         1
1        2                      Balls to the Wall         2
2        3                      Restless and Wild         2
3        4                      Let There Be Rock         1
4        5                               Big Ones         3

# And here we cna try to display interactively the tables inside.

So we can then perform  query and get a dataframe

In [ ]:
import sqlite3 as sq3
import pandas as pd
import ipywidgets as widgets
from IPython.display import display

# Connect to the SQLite database
path = '/content/data/chinook.db'
con = sq3.connect(path)

# Get table names
tables_query = "SELECT name FROM sqlite_master WHERE type='table';"
tables_df = pd.read_sql(tables_query, con)
table_names = tables_df['name'].tolist()

# Create dropdown widget
table_dropdown = widgets.Dropdown(
    options=table_names,
    description='Select Table:',
    disabled=False,
)

# Define what happens when a table is selected
def display_table(selected_table):
    query = f"SELECT * FROM {selected_table} LIMIT 10;"
    df = pd.read_sql(query, con)
    display(df)

# Create an interactive output
widgets.interact(display_table, selected_table=table_dropdown);